# 基础路径配置
base:
  root: "." # 项目根目录
  config: "${base.root}/config" # 配置文件目录
  common: "${base.root}/common" # 通用模块目录
  utils: "${base.root}/utils" # 工具函数目录
  test_cases: "${base.root}/testCases" # 测试用例目录
  test_data: "${base.root}/testData" # 测试数据目录

# 配置文件路径
config_files:
  main_config: "${base.config}/config.yaml" # 主配置文件
  path_config: "${base.config}/paths.yaml" # 路径配置文件本身
  api_config: "${base.test_data}/api_config.yaml" # API配置文件

# 测试相关路径
test_paths:
  test_cases: "${base.test_cases}" # 测试用例目录
  test_demo: "${base.test_cases}/test_demo.py" # 示例测试用例
  conftest: "${base.test_cases}/conftest.py" # pytest fixture配置
  test_data: "${base.test_data}" # 测试数据目录

# 日志和报告路径
reporting:
  logs: "${base.root}/logs" # 日志目录
  allure_results: "${base.root}/allure-results" # Allure报告结果目录
  allure_report: "${base.root}/report" # Allure报告目录

# 入口文件路径
entry:
  main: "${base.root}/main.py" # 主入口文件
